### PR TITLE
LibWeb/CSS: Make FontFaceSet extend EventTarget & implement event handlers

### PR DESCRIPTION
**Pull request by jamierocks**
Serenity PR: https://github.com/SerenityOS/serenity/pull/24540

### CODE REVIEW

**Comment by jamierocks** [comment]
I don't think the memory leak was introduced by the changes here - seems to involve LibVideo. Happy to be corrected though :)

**Comment by awesomekling** [comment]
The HTMLTrackElement change looks a little unrelated? :)

**Comment by jamierocks** [comment]
Oops, that's was part of something else I was working on last last night - pushed to wrong branch 🤦‍♂️

**Comment by jamierocks** [comment]
Commit dropped. A bit perplexed at why I pushed that to this branch.

**Pull request merged**
